[pytest]
pythonpath = . app
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

    ignore::DeprecationWarning:pkg_resources

[tool:pytest]

addopts = -W 'ignore::UserWarning:face_recognition_models'
